services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - observability

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'status']
      interval: 10s
      retries: 5
      start_period: 10s
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - observability

  notifications-api:
    build:
      context: .
      dockerfile: apps/notifications-api/Dockerfile
    container_name: notifications-api
    ports:
      - '3333:3333'
    environment:
      NODE_ENV: production
      PORT: 3333
      VAPID_PUBLIC_KEY: BPS6wW5zh_8hMTQm3empFWVmDB0JGnys9LJQ8oJpUOmpW3P75naV4ZCM00ahXJb-n9JdmIlMrf0xh3EbW4rj66c
      VAPID_PRIVATE_KEY: 8hinyDsE8VfbkNviZX8FnyQvkkxU1ZxmMXx8oThswlA
      RABBITMQ_URL: amqp://rabbitmq:5672
      LOG_LEVEL: info
      REDIS_URL: redis://redis:6379
    depends_on:
      loki:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - observability

  notifications-fe:
    build:
      context: .
      dockerfile: apps/notifications-fe/Dockerfile
    container_name: notifications-fe
    ports:
      - '4200:80'
    depends_on:
      - notifications-api
    networks:
      - observability

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
      - ./loki-data/wal:/wal
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:3100/ready']
      interval: 5s
      retries: 5
      start_period: 5s
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3001:3000'
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - observability

volumes:
  grafana-data:
  loki-data:
  loki-wal:

networks:
  observability:
    driver: bridge
